namespace MakanApp.Application.Messaging;

public static class MessagingErrorCodes
{
    public const string ConversationNotFound = "CONVERSATION_NOT_FOUND";
    public const string ConversationNotAllowed = "CONVERSATION_NOT_ALLOWED";
    public const string DirectRecipientNotAvailable = "DIRECT_RECIPIENT_NOT_AVAILABLE";
    public const string DirectConversationConflict = "DIRECT_CONVERSATION_CONFLICT";
    public const string MessageEmpty = "MESSAGE_EMPTY";
    public const string MessageTooLong = "MESSAGE_TOO_LONG";
    public const string MessageNotAllowed = "MESSAGE_NOT_ALLOWED";
    public const string MessageClientIdRequired = "MESSAGE_CLIENT_ID_REQUIRED";
    public const string MessageIdempotencyConflict = "MESSAGE_IDEMPOTENCY_CONFLICT";
    public const string MessagePageInvalid = "MESSAGE_PAGE_INVALID";
    public const string ParticipantNotActive = "PARTICIPANT_NOT_ACTIVE";
    public const string OrganizationScopeMismatch = "ORGANIZATION_SCOPE_MISMATCH";
    public const string ConcurrencyConflict = "CONCURRENCY_CONFLICT";
    public const string ManagedConversationInvalid = "MANAGED_CONVERSATION_INVALID";
    public const string ConversationCreationConflict = "CONVERSATION_CREATION_CONFLICT";
    public const string ConversationManagementNotAllowed = "CONVERSATION_MANAGEMENT_NOT_ALLOWED";
    public const string ConversationArchived = "CONVERSATION_ARCHIVED";
    public const string ParticipantAlreadyActive = "PARTICIPANT_ALREADY_ACTIVE";
    public const string ParticipantNotFound = "PARTICIPANT_NOT_FOUND";
    public const string ConversationRoleInvalid = "CONVERSATION_ROLE_INVALID";
    public const string LastOwnerRequired = "LAST_OWNER_REQUIRED";
    public const string OwnershipTransferNotFound = "OWNERSHIP_TRANSFER_NOT_FOUND";
    public const string OwnershipTransferConflict = "OWNERSHIP_TRANSFER_CONFLICT";
    public const string MessagePublishNotAllowed = "MESSAGE_PUBLISH_NOT_ALLOWED";
    public const string MessageNotFound = "MESSAGE_NOT_FOUND";
    public const string MessageNotEditable = "MESSAGE_NOT_EDITABLE";
    public const string MessageDeleted = "MESSAGE_DELETED";
    public const string MessageEditConflict = "MESSAGE_EDIT_CONFLICT";
    public const string MessageKindInvalid = "MESSAGE_KIND_INVALID";
    public const string MessageAttachmentRequired = "MESSAGE_ATTACHMENT_REQUIRED";
    public const string MessageAttachmentNotReady = "MESSAGE_ATTACHMENT_NOT_READY";
    public const string MessageAttachmentNotAllowed = "MESSAGE_ATTACHMENT_NOT_ALLOWED";
    public const string MessageReplyNotAllowed = "MESSAGE_REPLY_NOT_ALLOWED";
    public const string MessageForwardNotAllowed = "MESSAGE_FORWARD_NOT_ALLOWED";
    public const string MessageForwardScopeNotAllowed = "MESSAGE_FORWARD_SCOPE_NOT_ALLOWED";
    public const string ReactionNotAllowed = "REACTION_NOT_ALLOWED";
    public const string MentionNotAllowed = "MENTION_NOT_ALLOWED";
    public const string PinNotAllowed = "PIN_NOT_ALLOWED";
    public const string FileNotAllowed = "FILE_NOT_ALLOWED";
    public const string ChangeCursorInvalid = "CHANGE_CURSOR_INVALID";
    public const string ReadCursorInvalid = "READ_CURSOR_INVALID";
    public const string DeliveryCursorInvalid = "DELIVERY_CURSOR_INVALID";
    public const string RealtimeSubscriptionNotAllowed = "REALTIME_SUBSCRIPTION_NOT_ALLOWED";
    public const string SearchQueryRequired = "SEARCH_QUERY_REQUIRED";
    public const string SearchQueryInvalid = "SEARCH_QUERY_INVALID";
    public const string SearchCursorInvalid = "SEARCH_CURSOR_INVALID";
    public const string SearchNotAllowed = "SEARCH_NOT_ALLOWED";
    public const string UserBlockNotAllowed = "USER_BLOCK_NOT_ALLOWED";
    public const string ReportNotAllowed = "REPORT_NOT_ALLOWED";
    public const string ReportMessageNotFound = "REPORT_MESSAGE_NOT_FOUND";
    public const string ReportIdempotencyConflict = "REPORT_IDEMPOTENCY_CONFLICT";
}
