// <auto-generated />
using System;
using MakanApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakanApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MakanDbContext))]
    [Migration("20260929131234_AddGuardianRelations")]
    partial class AddGuardianRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MakanApp.Domain.Guardian.GuardianRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("GuardianUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearnerOrganizationPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("GuardianUserId");

                    b.HasIndex("OrganizationId", "LearnerOrganizationPersonId");

                    b.HasIndex("OrganizationId", "GuardianUserId", "LearnerOrganizationPersonId")
                        .IsUnique()
                        .HasDatabaseName("UX_GuardianRelations_Active_Organization_Guardian_Learner")
                        .HasFilter("[Status] = 2 AND [EndedAtUtc] IS NULL");

                    b.ToTable("GuardianRelations", "guardian", t =>
                        {
                            t.HasCheckConstraint("CK_GuardianRelations_Status", "[Status] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MaxFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPhoneNumber", "CreatedAtUtc")
                        .HasDatabaseName("IX_OtpChallenges_Phone_CreatedAtUtc");

                    b.ToTable("OtpChallenges", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Persons", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("NormalizedUsername")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProfileCompletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUsername")
                        .HasFilter("[NormalizedUsername] IS NOT NULL");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VerifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Kind", "NormalizedIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UX_UserCredentials_Kind_Identifier");

                    b.ToTable("UserCredentials", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SelectedMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedRole")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("SelectedSubjectOrganizationPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_UserSessions_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("AcceptedMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedRoleAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeclinedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("DestinationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedMembershipId");

                    b.HasIndex("AcceptedRoleAssignmentId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("DestinationUserId", "OrganizationId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UX_Invitations_Pending_Destination_Organization_Role")
                        .HasFilter("[Status] = 1");

                    b.ToTable("Invitations", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_Invitations_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_Invitations_Role", "[Role] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Invitations_Status", "[Status] IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Memberships_Active_User_Organization")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("Memberships", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_Memberships_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Organizations", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_Organizations_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.OrganizationPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("UQ_OrganizationPersons_OrganizationId_Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("OrganizationId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrganizationPersons_Active_Organization_Person")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("OrganizationPersons", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationPersons_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UX_RoleAssignments_Active_Membership_Role")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("RoleAssignments", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_RoleAssignments_Role", "[Role] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_RoleAssignments_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Guardian.GuardianRelation", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("GuardianUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.OrganizationPerson", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LearnerOrganizationPersonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.User", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.Person", null)
                        .WithOne()
                        .HasForeignKey("MakanApp.Domain.Identity.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserCredential", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Invitation", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Membership", null)
                        .WithMany()
                        .HasForeignKey("AcceptedMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MakanApp.Domain.Organization.RoleAssignment", null)
                        .WithMany()
                        .HasForeignKey("AcceptedRoleAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DestinationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Membership", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.OrganizationPerson", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Identity.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.RoleAssignment", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Membership", null)
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
