// <auto-generated />
using System;
using MakanApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakanApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MakanDbContext))]
    [Migration("20260930123228_AddSessionsAndAttendance")]
    partial class AddSessionsAndAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MakanApp.Domain.Academic.AcademicPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("UQ_AcademicPeriods_OrganizationId_Id");

                    b.ToTable("AcademicPeriods", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_AcademicPeriods_DateRange", "[EndDate] > [StartDate]");

                            t.HasCheckConstraint("CK_AcademicPeriods_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("RecordedByMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "ClassId", "SessionId", "EnrollmentId", "Id")
                        .HasName("UQ_Attendance_Context_Id");

                    b.HasIndex("OrganizationId", "RecordedByMembershipId");

                    b.HasIndex("OrganizationId", "ClassId", "EnrollmentId");

                    b.HasIndex("OrganizationId", "SessionId", "EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Attendance_Organization_Session_Enrollment");

                    b.ToTable("Attendance", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_Attendance_Status", "[Status] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.AttendanceRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CorrectedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("CorrectedByMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CorrectedByMembershipId");

                    b.HasIndex("OrganizationId", "ClassId", "SessionId", "EnrollmentId", "AttendanceId");

                    b.ToTable("AttendanceRevisions", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRevisions_NewStatus", "[NewStatus] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_AttendanceRevisions_PreviousStatus", "[PreviousStatus] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_AttendanceRevisions_StatusChanged", "[PreviousStatus] <> [NewStatus]");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("UQ_Classes_OrganizationId_Id");

                    b.HasIndex("OrganizationId", "AcademicPeriodId");

                    b.HasIndex("OrganizationId", "CourseId");

                    b.ToTable("Classes", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_Classes_Capacity", "[Capacity] > 0");

                            t.HasCheckConstraint("CK_Classes_Status", "[Status] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("UQ_Courses_OrganizationId_Id");

                    b.ToTable("Courses", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("LearnerOrganizationPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "ClassId", "Id")
                        .HasName("UQ_Enrollments_OrganizationId_ClassId_Id");

                    b.HasIndex("OrganizationId", "LearnerOrganizationPersonId");

                    b.HasIndex("OrganizationId", "ClassId", "LearnerOrganizationPersonId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollments_Active_Organization_Class_Learner")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("Enrollments", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_Enrollments_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.ScheduleRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveUntil")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("LocalDayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("LocalStartTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "ClassId", "Id")
                        .HasName("UQ_ScheduleRules_OrganizationId_ClassId_Id");

                    b.ToTable("ScheduleRules", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduleRules_DateRange", "[EffectiveUntil] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_ScheduleRules_Duration", "[DurationMinutes] > 0 AND [DurationMinutes] <= 1440");

                            t.HasCheckConstraint("CK_ScheduleRules_LocalDayOfWeek", "[LocalDayOfWeek] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_ScheduleRules_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("OccurrenceLocalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("ScheduleRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "ClassId", "Id")
                        .HasName("UQ_Sessions_OrganizationId_ClassId_Id");

                    b.HasIndex("OrganizationId", "ClassId", "ScheduleRuleId");

                    b.HasIndex("OrganizationId", "ScheduleRuleId", "OccurrenceLocalDate")
                        .IsUnique()
                        .HasDatabaseName("UX_Sessions_ScheduleRule_Occurrence")
                        .HasFilter("[Status] = 1 AND [ScheduleRuleId] IS NOT NULL AND [OccurrenceLocalDate] IS NOT NULL");

                    b.HasIndex("OrganizationId", "ClassId", "StartUtc", "EndUtc")
                        .HasDatabaseName("IX_Sessions_Organization_Class_Time");

                    b.ToTable("Sessions", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_Sessions_Status", "[Status] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Sessions_TimeRange", "[EndUtc] > [StartUtc]");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.TeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "TeacherMembershipId");

                    b.HasIndex("OrganizationId", "ClassId", "TeacherMembershipId")
                        .IsUnique()
                        .HasDatabaseName("UX_TeacherAssignments_Active_Organization_Class_Teacher")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("TeacherAssignments", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherAssignments_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Guardian.GuardianRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("GuardianUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearnerOrganizationPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("GuardianUserId");

                    b.HasIndex("OrganizationId", "LearnerOrganizationPersonId");

                    b.HasIndex("OrganizationId", "GuardianUserId", "LearnerOrganizationPersonId")
                        .IsUnique()
                        .HasDatabaseName("UX_GuardianRelations_Active_Organization_Guardian_Learner")
                        .HasFilter("[Status] = 2 AND [EndedAtUtc] IS NULL");

                    b.ToTable("GuardianRelations", "guardian", t =>
                        {
                            t.HasCheckConstraint("CK_GuardianRelations_Status", "[Status] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MaxFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPhoneNumber", "CreatedAtUtc")
                        .HasDatabaseName("IX_OtpChallenges_Phone_CreatedAtUtc");

                    b.ToTable("OtpChallenges", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Persons", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("NormalizedUsername")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProfileCompletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUsername")
                        .HasFilter("[NormalizedUsername] IS NOT NULL");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VerifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Kind", "NormalizedIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UX_UserCredentials_Kind_Identifier");

                    b.ToTable("UserCredentials", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SelectedMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedRole")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("SelectedSubjectOrganizationPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_UserSessions_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", "identity");
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("AcceptedMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedRoleAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeclinedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("DestinationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedMembershipId");

                    b.HasIndex("AcceptedRoleAssignmentId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("DestinationUserId", "OrganizationId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UX_Invitations_Pending_Destination_Organization_Role")
                        .HasFilter("[Status] = 1");

                    b.ToTable("Invitations", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_Invitations_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_Invitations_Role", "[Role] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Invitations_Status", "[Status] IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("UQ_Memberships_OrganizationId_Id");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Memberships_Active_User_Organization")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("Memberships", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_Memberships_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Organizations", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_Organizations_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.OrganizationPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("UQ_OrganizationPersons_OrganizationId_Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("OrganizationId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrganizationPersons_Active_Organization_Person")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("OrganizationPersons", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationPersons_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UX_RoleAssignments_Active_Membership_Role")
                        .HasFilter("[Status] = 1 AND [EndedAtUtc] IS NULL");

                    b.ToTable("RoleAssignments", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_RoleAssignments_Role", "[Role] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_RoleAssignments_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.AcademicPeriod", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Attendance", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecordedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Academic.Enrollment", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId", "EnrollmentId")
                        .HasPrincipalKey("OrganizationId", "ClassId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Academic.Session", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId", "SessionId")
                        .HasPrincipalKey("OrganizationId", "ClassId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.AttendanceRevision", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CorrectedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Academic.Attendance", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId", "SessionId", "EnrollmentId", "AttendanceId")
                        .HasPrincipalKey("OrganizationId", "ClassId", "SessionId", "EnrollmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Class", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Academic.AcademicPeriod", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AcademicPeriodId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Academic.Course", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CourseId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Course", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Enrollment", b =>
                {
                    b.HasOne("MakanApp.Domain.Academic.Class", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.OrganizationPerson", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LearnerOrganizationPersonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.ScheduleRule", b =>
                {
                    b.HasOne("MakanApp.Domain.Academic.Class", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.Session", b =>
                {
                    b.HasOne("MakanApp.Domain.Academic.Class", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Academic.ScheduleRule", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId", "ScheduleRuleId")
                        .HasPrincipalKey("OrganizationId", "ClassId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MakanApp.Domain.Academic.TeacherAssignment", b =>
                {
                    b.HasOne("MakanApp.Domain.Academic.Class", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClassId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeacherMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Guardian.GuardianRelation", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("GuardianUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.OrganizationPerson", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LearnerOrganizationPersonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.User", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.Person", null)
                        .WithOne()
                        .HasForeignKey("MakanApp.Domain.Identity.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserCredential", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Invitation", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Membership", null)
                        .WithMany()
                        .HasForeignKey("AcceptedMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MakanApp.Domain.Organization.RoleAssignment", null)
                        .WithMany()
                        .HasForeignKey("AcceptedRoleAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DestinationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.Membership", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.OrganizationPerson", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakanApp.Domain.Identity.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MakanApp.Domain.Organization.RoleAssignment", b =>
                {
                    b.HasOne("MakanApp.Domain.Organization.Membership", null)
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
