<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>MakanApp-7d9c51a7-2dc8-4e2b-bf05-ae9546871542</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MakanApp.Application\MakanApp.Application.csproj" />
    <ProjectReference Include="..\MakanApp.Infrastructure\MakanApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>